### ISSUE TITLE
Where is rsa~ function?

### ISSUE THREAD

**Issue by SeojinYoon** [eberlot/motor_sequence_learning#1]
Hi,I have been found the rsa_classicalMDS function for replicating this paper.

But I can't replicate because of the rsa_~~ functions. ex) rsa_classicalMDS

Which package has the rsa_classicalMDS function?
for reference, I can't found in rsa-toolbox matlab
"https://github.com/rsagroup/rsatoolbox_matlab"

Please help me!

**Comment by eberlot** [comment]
Hi - correct, this is from an earlier version of the github repository, development branch. In the current version, the equivalent function is rsa.MDSRDMs (so MDSRDMs in the rsa+ folder).

**Comment by SeojinYoon** [comment]
Thank you!

**Comment by SeojinYoon** [comment]
I can't run code using rsa.MDSRDMs.
I think function's argument format is changed as the version is changed.

I try to convert the function but It is too hard for me...
Can you refer to the previous version of the github repository?
